# 使用 Debian 版 Ruby 镜像
FROM ruby:3.2-slim

WORKDIR /workspace

# 先复制依赖文件，安装依赖，利用缓存
COPY Gemfile ./
RUN apt-get update && \
    apt-get install -y build-essential nodejs && \
    gem install bundler jekyll && \
    bundle install

# 再复制项目其他文件
COPY . .
