version: "3.8"
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: jere/jekyll-blog:latest
    ports:
      - "28090:80"
    container_name: jere-jekyll-blog
    networks:
      - jere-net

networks:
  jere-net:
    external: true
